### ISSUE TITLE
libusb become deadlock or segment fault when i'm using async and do hotplug, how to fix it?

### ISSUE THREAD

**Issue by felixxue** [libusb/libusb#39] opened 2014-11-14 03:47 UTC
my platform is arm-linux, libusb version is 1.0.15, to increase transfer speed, i use async api, one thread to do event handle, and other threads to receive or send. 
when i did hotplug action:
1. sometimes libusb become deadlock, the recv or send thread dead in libusb_submit_transfer, the event handle thread dead in usbi_handle_disconnect.
2. and sometimes libusb become segment fault, also in usbi_handle_disconnect->usbi_handle_transfer_completion
i try to upgrade libusb to 1.0.19, but it also remains.
how to fix it, thanks.

**Comment by dickens** [comment] 2015-01-11 08:20
Can you provide a debug log when these issues occur?

**Comment by dickens** [comment] 2015-04-28 20:49
Closing due to lack or response from reporter. This can be re-opened if the issue is still found to occur.

**Closed by dickens** 2015-04-28 20:49 UTC
