### ISSUE TITLE
Problems sending to and receiving data from the IC-R8600

### ISSUE THREAD

**Issue by righthalfplane** [libusb/libusb#837] opened 2021-01-05 00:24 UTC
Something strange going on - the idVendor vendor comes up as 0x0c26, but the iProduct comes up as 0x0023 on Windows and as 0x0022 on macOS and ubuntu 18.04. I wrote a little program to set one of the  IC-R8600 modes - It works perfectly on Windows 7 and Windows 10, but it errors on the MacOS High Sierra and Ubuntu 18.04 . If just set the iProduct to 0x0022, I get the "MacOS - output 1". If just set the iProduct to 0x0022 and also do the libusb_set_interface_alt_setting also, I get the "MacOS - output 2" - it just times output, but everything else looks Ok.

```
#include <stdio.h>
#include <stdlib.h>
#include <libusb-1.0/libusb.h>

// cc -o usbTry3 usbTry3.c -lusb-1.0

int main()
{
	libusb_context *ctx;
	libusb_device_handle *handle;

	libusb_init(&ctx);
	//libusb_set_debug(ctx, 3);
	libusb_set_option(ctx, LIBUSB_OPTION_LOG_LEVEL, LIBUSB_LOG_LEVEL_DEBUG);
	handle = libusb_open_device_with_vid_pid(ctx, 0x0c26, 0x0023);
	//handle = libusb_open_device_with_vid_pid(ctx, 0x0c26, 0x0022);
	if(handle == NULL){printf("libusb_open_device_with_vid_pid failed\n");exit(1);}
	//libusb_set_configuration(handle, 1);
	
	int e=libusb_claim_interface(handle,0);
	if(e != 0){printf("libusb_claim_interface error %d\n",e);return 1;}

	//e=libusb_set_interface_alt_setting(handle,0,1);
	//if(e != 0){printf("libusb_set_interface_alt_setting error %d\n",e);return 1;}


	{
		unsigned char cmd[] = { 0xFE, 0xFE, 0x96, 0xE0,  0x1A, 0x13, 0x00, 0x01,  0xFD, 0xFF };
		
		int transferred;
		transferred=0;
		e=libusb_bulk_transfer(handle, 0X02,cmd,(int)sizeof(cmd), &transferred,2000);
	    if(e != 0)printf("libusb_bulk_transfer1 %d\n",e);
	    printf(" transferred %d\n",transferred);
		transferred=0;
		e=libusb_bulk_transfer(handle, 0X88,cmd,(int)sizeof(cmd), &transferred,2000);
	    if(e != 0)printf("libusb_bulk_transfer2 %d\n",e);
	    printf(" transferred %d\n",transferred);

	}



	libusb_release_interface(handle, 0);
	libusb_close(handle);
	libusb_exit(ctx);
	return 0;
}
```

Windows output -
```
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.003507] [00000a34] libusb: debug [libusb_get_device_list]
[ 0.007991] [00000a34] libusb: debug [winusb_get_device_list] allocating new device for session [53]
[ 0.008121] [00000a34] libusb: debug [winusb_get_device_list] allocating new device for session [54]
[ 0.008317] [00000a34] libusb: debug [get_api_type] driver(s): RtlWlanu_OldIC
[ 0.008419] [00000a34] libusb: debug [get_api_type] upper filter driver(s): vwifibus
[ 0.008515] [00000a34] libusb: debug [winusb_get_device_list] allocating new device for session [18]
[ 0.008660] [00000a34] libusb: debug [get_api_type] driver(s): WinUsb
[ 0.008727] [00000a34] libusb: debug [get_api_type] matched driver name against WinUSB
[ 0.008772] [00000a34] libusb: debug [winusb_get_device_list] allocating new device for session [2D]
[ 0.008906] [00000a34] libusb: debug [get_api_type] driver(s): HidUsb
[ 0.008978] [00000a34] libusb: debug [get_api_type] matched driver name against HID API
[ 0.009023] [00000a34] libusb: debug [winusb_get_device_list] allocating new device for session [40]
[ 0.009104] [00000a34] libusb: debug [get_api_type] driver(s): usbccgp
[ 0.009137] [00000a34] libusb: debug [get_api_type] matched driver name against Composite API
[ 0.009154] [00000a34] libusb: debug [winusb_get_device_list] allocating new device for session [41]
[ 0.009245] [00000a34] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_10DE&DEV_1ADA&SUBSYS_C7521462&REV_A1\4&37732CF4&0&0208' bus number 1
[ 0.009290] [00000a34] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_8086&DEV_A36D&SUBSYS_50071458&REV_10\3&11583659&0&A0' bus number 2
[ 0.009747] [00000a34] libusb: debug [winusb_get_device_list] found existing device for session [41]
[ 0.009798] [00000a34] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.009821] [00000a34] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 59 bytes)
[ 0.009849] [00000a34] libusb: debug [init_device] (bus: 2, addr: 3, depth: 1, port: 6): 'USB\VID_0461&PID_4E6F\5&356B5377&0&6'
[ 0.009926] [00000a34] libusb: debug [init_device] (bus: 2, addr: 0, depth: 0, port: 0): 'USB\ROOT_HUB30\4&2720BDB3&0&0'
[ 0.009984] [00000a34] libusb: debug [winusb_get_device_list] extra GUID: {68D5F5EE-B0E7-49FD-A0D5-5B10842656B7}
[ 0.010007] [00000a34] libusb: debug [winusb_get_device_list] found existing device for session [2D]
[ 0.010047] [00000a34] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.010272] [00000a34] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 39 bytes)
[ 0.010466] [00000a34] libusb: debug [init_device] (bus: 2, addr: 16, depth: 1, port: 8): 'USB\VID_0C26&PID_0023\5&356B5377&0&8'
[ 0.010744] [00000a34] libusb: debug [winusb_get_device_list] found existing device for session [18]
[ 0.010946] [00000a34] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.011285] [00000a34] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 46 bytes)
[ 0.011325] [00000a34] libusb: debug [init_device] (bus: 2, addr: 2, depth: 1, port: 2): 'USB\VID_0BDA&PID_8178\00E04C000001'
[ 0.011395] [00000a34] libusb: debug [winusb_get_device_list] found existing device for session [40]
[ 0.011580] [00000a34] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.011768] [00000a34] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 34 bytes)
[ 0.011805] [00000a34] libusb: debug [init_device] (bus: 2, addr: 1, depth: 1, port: 5): 'USB\VID_046D&PID_C03D\5&356B5377&0&5'
[ 0.013439] [00000a34] libusb: debug [init_device] (bus: 1, addr: 0, depth: 0, port: 0): 'USB\ROOT_HUB30\5&22058B9C&0&0'
[ 0.014066] [00000a34] libusb: debug [winusb_get_device_list] setting HID interface for [40]:
[ 0.014095] [00000a34] libusb: debug [set_hid_interface] interface[0] = \\.\HID#VID_046D&PID_C03D#6&292AE4E5&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.014322] [00000a34] libusb: debug [winusb_get_device_list] setting composite interface for [41]:
[ 0.014347] [00000a34] libusb: debug [set_composite_interface] interface[1] = \\.\HID#VID_0461&PID_4E6F&MI_01&COL01#7&367148CE&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.014386] [00000a34] libusb: debug [winusb_get_device_list] setting composite interface for [41]:
[ 0.014531] [00000a34] libusb: debug [set_composite_interface] interface[1] already set - ignoring HID collection: HID\VID_0461&PID_4E6F&MI_01&COL02\7&367148CE&0&0001
[ 0.014578] [00000a34] libusb: debug [winusb_get_device_list] setting composite interface for [41]:
[ 0.014719] [00000a34] libusb: debug [set_composite_interface] interface[0] = \\.\HID#VID_0461&PID_4E6F&MI_00#7&129A0B0C&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}#KBD
[ 0.014954] [00000a34] libusb: debug [get_api_type] driver(s): WinUsb
[ 0.014995] [00000a34] libusb: debug [get_api_type] matched driver name against WinUSB
[ 0.015279] [00000a34] libusb: debug [libusb_get_device_descriptor]
[ 0.015303] [00000a34] libusb: debug [libusb_get_device_descriptor]
[ 0.015457] [00000a34] libusb: debug [libusb_get_device_descriptor]
[ 0.015612] [00000a34] libusb: debug [libusb_open] open 2.16
[ 0.015794] [00000a34] libusb: debug [libusb_unref_device] destroy device 2.3
[ 0.015922] [00000a34] libusb: debug [libusb_unref_device] destroy device 2.2
[ 0.016075] [00000a34] libusb: debug [libusb_unref_device] destroy device 2.1
[ 0.016242] [00000a34] libusb: debug [libusb_unref_device] destroy device 1.0
[ 0.016395] [00000a34] libusb: debug [libusb_claim_interface] interface 0
[ 0.016600] [00000a34] libusb: debug [winusbx_claim_interface] claimed interface 0
[ 0.016754] [00000a34] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 02 to interface 0
[ 0.017024] [00000a34] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 86 to interface 0
[ 0.017149] [00000a34] libusb: debug [windows_assign_endpoints] (re)assigned endpoint 88 to interface 0
[ 0.017468] [00000a34] libusb: debug [libusb_alloc_transfer] transfer 00000268D96D2058
[ 0.017568] [00000a34] libusb: debug [libusb_submit_transfer] transfer 00000268D96D2058
[ 0.017792] [00000a34] libusb: debug [usbi_add_pollfd] add fd 2 events 4
[ 0.017875] [00000a34] libusb: debug [winusbx_submit_bulk_transfer] matched endpoint 02 with interface 0
[ 0.018031] [00000a34] libusb: debug [winusbx_submit_bulk_transfer] writing 10 bytes
[ 0.018242] [00000a34] libusb: debug [libusb_get_next_timeout] next timeout in 1.999500s
[ 0.018339] [00000a34] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.018493] [00000a34] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.018642] [00000a34] libusb: debug [handle_events] poll() 2 fds with timeout in 2000ms
[ 0.018794] [00000a34] libusb: debug [handle_events] poll() returned 1
[ 0.018945] [00000a34] libusb: debug [windows_handle_events] checking fd 2 with revents = 0004
[ 0.019099] [00000a34] libusb: debug [usbi_remove_pollfd] remove fd 2
[ 0.019252] [00000a34] libusb: debug [windows_transfer_callback] handling I/O completion with errcode 0, size 10
[ 0.019382] [00000a34] libusb: debug [usbi_handle_transfer_completion] transfer 00000268D96D2058 has callback 00007FFE72438CE0
[ 0.019546] [00000a34] libusb: debug [sync_transfer_cb] actual_length=10
[ 0.019694] [00000a34] libusb: debug [libusb_free_transfer] transfer 00000268D96D2058
 transferred 10
[ 0.019998] [00000a34] libusb: debug [libusb_alloc_transfer] transfer 00000268D96D2058
[ 0.020146] [00000a34] libusb: debug [libusb_submit_transfer] transfer 00000268D96D2058
[ 0.020351] [00000a34] libusb: debug [usbi_add_pollfd] add fd 2 events 1
[ 0.020471] [00000a34] libusb: debug [winusbx_submit_bulk_transfer] matched endpoint 88 with interface 0
[ 0.020628] [00000a34] libusb: debug [winusbx_submit_bulk_transfer] reading 10 bytes
[ 0.020827] [00000a34] libusb: debug [libusb_get_next_timeout] next timeout in 1.999500s
[ 0.020947] [00000a34] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.021103] [00000a34] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.021254] [00000a34] libusb: debug [handle_events] poll() 2 fds with timeout in 2000ms
[ 0.026118] [00000a34] libusb: debug [handle_events] poll() returned 1
[ 0.026146] [00000a34] libusb: debug [windows_handle_events] checking fd 2 with revents = 0001
[ 0.026171] [00000a34] libusb: debug [usbi_remove_pollfd] remove fd 2
[ 0.026416] [00000a34] libusb: debug [windows_transfer_callback] handling I/O completion with errcode 0, size 6
[ 0.026667] [00000a34] libusb: debug [usbi_handle_transfer_completion] transfer 00000268D96D2058 has callback 00007FFE72438CE0
[ 0.026923] [00000a34] libusb: debug [sync_transfer_cb] actual_length=6
[ 0.027127] [00000a34] libusb: debug [libusb_free_transfer] transfer 00000268D96D2058
 transferred 6
[ 0.027947] [00000a34] libusb: debug [libusb_release_interface] interface 0
[ 0.028008] [00000a34] libusb: debug [libusb_close]
[ 0.028205] [00000a34] libusb: debug [libusb_unref_device] destroy device 2.16
[ 0.028388] [00000a34] libusb: debug [libusb_unref_device] destroy device 2.0
[ 0.028454] [00000a34] libusb: debug [libusb_exit]
[ 0.028597] [00000a34] libusb: debug [libusb_exit] destroying default context
[ 0.028621] [00000a34] libusb: debug [usbi_remove_pollfd] remove fd 0
[ 0.029269] [00001374] libusb: debug [windows_clock_gettime_threaded] timer thread quitting

C:\Users\Owner\Documents\Archive\SdrGlut-780\misc\usb-example\SampleSDR11\x64\Release\SampleSDR.exe (process 1448) exited with code 0.
Press any key to close this window . . .
```

MacOS - output 1

```
[dir:SdrGlut-780/misc/usb-example] dir% usbTry3
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.004752] [00000307] libusb: debug [libusb_get_device_list] 
[ 0.004820] [00000307] libusb: debug [discovered_devs_append] need to increase capacity
[ 0.004836] [00000307] libusb: debug [libusb_get_device_descriptor] 
[ 0.004839] [00000307] libusb: debug [libusb_open] open 0.6
[ 0.004950] [00000307] libusb: debug [darwin_open] device open for access
[ 0.004958] [00000307] libusb: debug [libusb_claim_interface] interface 0
[ 0.005337] [00000307] libusb: debug [get_endpoints] building table of endpoints.
[ 0.005374] [00000307] libusb: debug [darwin_claim_interface] interface opened
[ 0.005393] [00000307] libusb: debug [libusb_alloc_transfer] transfer 0x7fed73601048
[ 0.005400] [00000307] libusb: debug [libusb_submit_transfer] transfer 0x7fed73601048
[ 0.005407] [00000307] libusb: debug [ep_to_pipeRef] converting ep address 0x02 to pipeRef and interface
[ 0.005410] [00000307] libusb: warning [ep_to_pipeRef] no pipeRef found with endpoint address 0x02.
[ 0.005413] [00000307] libusb: error [submit_bulk_transfer] endpoint not found on any open interface
[ 0.005416] [00000307] libusb: debug [libusb_free_transfer] transfer 0x7fed73601048
libusb_bulk_transfer1 -5
 transferred 0
[ 0.005446] [00000307] libusb: debug [libusb_alloc_transfer] transfer 0x7fed73601048
[ 0.005449] [00000307] libusb: debug [libusb_submit_transfer] transfer 0x7fed73601048
[ 0.005452] [00000307] libusb: debug [ep_to_pipeRef] converting ep address 0x88 to pipeRef and interface
[ 0.005455] [00000307] libusb: warning [ep_to_pipeRef] no pipeRef found with endpoint address 0x88.
[ 0.005458] [00000307] libusb: error [submit_bulk_transfer] endpoint not found on any open interface
[ 0.005460] [00000307] libusb: debug [libusb_free_transfer] transfer 0x7fed73601048
libusb_bulk_transfer2 -5
 transferred 0
[ 0.005469] [00000307] libusb: debug [libusb_release_interface] interface 0
[ 0.005602] [00000307] libusb: debug [libusb_close] 
[ 0.005641] [00000307] libusb: debug [libusb_exit] 
[ 0.005646] [00000307] libusb: debug [libusb_exit] destroying default context
[ 0.005652] [00000307] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 0.005663] [00000307] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.005673] [00000307] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.005685] [00000307] libusb: debug [handle_events] poll() 1 fds with timeout in 0ms
[ 0.005700] [00000307] libusb: debug [handle_events] poll() returned 0
[ 0.005704] [00000307] libusb: debug [libusb_unref_device] destroy device 0.6
[ 0.005707] [00000307] libusb: debug [libusb_unref_device] destroy device 0.4
[ 0.005710] [00000307] libusb: debug [libusb_unref_device] destroy device 0.3
[ 0.005713] [00000307] libusb: debug [libusb_unref_device] destroy device 0.2
[ 0.005716] [00000307] libusb: debug [libusb_unref_device] destroy device 0.1
[ 0.005719] [00000307] libusb: debug [libusb_unref_device] destroy device 29.4
[ 0.005722] [00000307] libusb: debug [libusb_unref_device] destroy device 29.2
[ 0.005725] [00000307] libusb: debug [libusb_unref_device] destroy device 29.1
[ 0.005728] [00000307] libusb: debug [libusb_unref_device] destroy device 29.0
[ 0.005731] [00000307] libusb: debug [libusb_unref_device] destroy device 29.0
[ 0.005734] [00000307] libusb: debug [usbi_remove_pollfd] remove fd 3
[ 0.005786] [00001507] libusb: debug [darwin_event_thread_main] darwin event thread exiting
[dir:SdrGlut-780/misc/usb-example] dir% 

```
MacOS output 2
```
[dir:SdrGlut-780/misc/usb-example] dir% usbTry3
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.004722] [00000307] libusb: debug [libusb_get_device_list] 
[ 0.004802] [00000307] libusb: debug [discovered_devs_append] need to increase capacity
[ 0.004818] [00000307] libusb: debug [libusb_get_device_descriptor] 
[ 0.004821] [00000307] libusb: debug [libusb_open] open 0.8
[ 0.004934] [00000307] libusb: debug [darwin_open] device open for access
[ 0.004943] [00000307] libusb: debug [libusb_claim_interface] interface 0
[ 0.004963] [00000307] libusb: info [darwin_claim_interface] no interface found; setting configuration: 1
[ 0.007351] [00000307] libusb: debug [get_endpoints] building table of endpoints.
[ 0.007393] [00000307] libusb: debug [darwin_claim_interface] interface opened
[ 0.007400] [00000307] libusb: debug [libusb_set_interface_alt_setting] interface 0 altsetting 1
[ 0.009467] [00000307] libusb: debug [get_endpoints] building table of endpoints.
[ 0.009486] [00000307] libusb: debug [get_endpoints] interface: 0 pipe 1: dir: 0 number: 1
[ 0.009495] [00000307] libusb: debug [get_endpoints] interface: 0 pipe 2: dir: 1 number: 1
[ 0.009502] [00000307] libusb: debug [get_endpoints] interface: 0 pipe 3: dir: 0 number: 2
[ 0.009509] [00000307] libusb: debug [get_endpoints] interface: 0 pipe 4: dir: 0 number: 4
[ 0.009516] [00000307] libusb: debug [get_endpoints] interface: 0 pipe 5: dir: 1 number: 6
[ 0.009523] [00000307] libusb: debug [get_endpoints] interface: 0 pipe 6: dir: 1 number: 8
[ 0.009543] [00000307] libusb: debug [libusb_alloc_transfer] transfer 0x7fb45b800828
[ 0.009551] [00000307] libusb: debug [libusb_submit_transfer] transfer 0x7fb45b800828
[ 0.009558] [00000307] libusb: debug [ep_to_pipeRef] converting ep address 0x02 to pipeRef and interface
[ 0.009562] [00000307] libusb: debug [ep_to_pipeRef] pipe 3 on interface 0 matches
[ 0.009596] [00000307] libusb: debug [libusb_get_next_timeout] no URB with timeout or all handled by OS; no timeout!
[ 0.009612] [00000307] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.009624] [00000307] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.009637] [00000307] libusb: debug [handle_events] poll() 1 fds with timeout in 60000ms
[ 2.066251] [00001507] libusb: debug [darwin_async_io_callback] an async io operation has completed
[ 2.066285] [00000307] libusb: debug [handle_events] poll() returned 1
[ 2.066296] [00000307] libusb: debug [handle_events] caught a fish on the event pipe
[ 2.066299] [00000307] libusb: debug [darwin_handle_transfer_completion] handling bulk completion with kernel status -536854447
[ 2.066303] [00000307] libusb: warning [darwin_transfer_status] transfer error: timed out
[ 2.066307] [00000307] libusb: debug [usbi_handle_transfer_completion] transfer 0x7fb45b800828 has callback 0x1022e0f30
[ 2.066329] [00000307] libusb: debug [sync_transfer_cb] actual_length=0
[ 2.066406] [00000307] libusb: debug [libusb_free_transfer] transfer 0x7fb45b800828
libusb_bulk_transfer1 -7
 transferred 0
[ 2.066457] [00000307] libusb: debug [libusb_alloc_transfer] transfer 0x7fb4595081f8
[ 2.066461] [00000307] libusb: debug [libusb_submit_transfer] transfer 0x7fb4595081f8
[ 2.066464] [00000307] libusb: debug [ep_to_pipeRef] converting ep address 0x88 to pipeRef and interface
[ 2.066468] [00000307] libusb: debug [ep_to_pipeRef] pipe 6 on interface 0 matches
[ 2.066516] [00000307] libusb: debug [libusb_get_next_timeout] no URB with timeout or all handled by OS; no timeout!
[ 2.066522] [00000307] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 2.066525] [00000307] libusb: debug [handle_events] poll() 1 fds with timeout in 60000ms
[ 4.103198] [00001507] libusb: debug [darwin_async_io_callback] an async io operation has completed
[ 4.103227] [00000307] libusb: debug [handle_events] poll() returned 1
[ 4.103237] [00000307] libusb: debug [handle_events] caught a fish on the event pipe
[ 4.103240] [00000307] libusb: debug [darwin_handle_transfer_completion] handling bulk completion with kernel status -536854447
[ 4.103244] [00000307] libusb: warning [darwin_transfer_status] transfer error: timed out
[ 4.103247] [00000307] libusb: debug [usbi_handle_transfer_completion] transfer 0x7fb4595081f8 has callback 0x1022e0f30
[ 4.103250] [00000307] libusb: debug [sync_transfer_cb] actual_length=0
[ 4.103256] [00000307] libusb: debug [libusb_free_transfer] transfer 0x7fb4595081f8
libusb_bulk_transfer2 -7
 transferred 0
[ 4.103269] [00000307] libusb: debug [libusb_release_interface] interface 0
[ 4.105326] [00000307] libusb: debug [libusb_close] 
[ 4.105366] [00000307] libusb: debug [libusb_exit] 
[ 4.105371] [00000307] libusb: debug [libusb_exit] destroying default context
[ 4.105374] [00000307] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 4.105377] [00000307] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 4.105380] [00000307] libusb: debug [handle_events] poll() 1 fds with timeout in 0ms
[ 4.105388] [00000307] libusb: debug [handle_events] poll() returned 0
[ 4.105391] [00000307] libusb: debug [libusb_unref_device] destroy device 0.8
[ 4.105395] [00000307] libusb: debug [libusb_unref_device] destroy device 0.4
[ 4.105398] [00000307] libusb: debug [libusb_unref_device] destroy device 0.3
[ 4.105401] [00000307] libusb: debug [libusb_unref_device] destroy device 0.2
[ 4.105405] [00000307] libusb: debug [libusb_unref_device] destroy device 0.1
[ 4.105408] [00000307] libusb: debug [libusb_unref_device] destroy device 29.4
[ 4.105411] [00000307] libusb: debug [libusb_unref_device] destroy device 29.2
[ 4.105414] [00000307] libusb: debug [libusb_unref_device] destroy device 29.1
[ 4.105417] [00000307] libusb: debug [libusb_unref_device] destroy device 29.0
[ 4.105420] [00000307] libusb: debug [libusb_unref_device] destroy device 29.0
[ 4.105423] [00000307] libusb: debug [usbi_remove_pollfd] remove fd 3
[ 4.105483] [00001507] libusb: debug [darwin_event_thread_main] darwin event thread exiting
[dir:SdrGlut-780/misc/usb-example] dir% 
```

**Comment by mcuee** [comment] 2021-01-05 12:44
Please post the usb descriptor of the device (similar to "lsusb -vvv" under Linux). 
You can get "lsusb" formular from Homebrew for macOS which produce similar output to Linux "lsusb -vvv". 
Or you can post the output of USBView or similar utility under Windows, say usbtreeview.
https://www.uwe-sieber.de/usbtreeview_e.html

**Comment by mcuee** [comment] 2021-01-05 12:48
Also this github repo is for issue reporting and not for technical report. Please post your question to the mailing list, including the USB descriptors.

**Comment by mcuee** [comment] 2021-01-06 13:37
Basically you can not just use your windows code in Mac/Linux as the device is obviously different from Windows -- that is why the product ID is different. You have to figure out a way to send some command to to the device to make it switching to the "Windows" operating mode. You have to reverse engineering if you do not know the communication protocol.

I will close the issue for now. You can ask the question in libusb mailing list after you have done some more research about the device.

**Closed by mcuee** 2021-01-06 13:37 UTC
Labels: question

**Comment by mcuee** [comment] 2021-01-16 01:02
The issue is now discussed in the mailing list.
