### ISSUE TITLE
libusb_kernel_driver_active always return zero

### ISSUE THREAD

**Issue by alexbour** [libusb/libusb#805] opened 2020-11-01 15:31 UTC
I'm writing userland front end FOR RHEL8.2   to communicate with Ti's launchpad. Whenever I call libusb_kernel_driver_active, the response is always zero, while no driver seems to be attached to the device. therefore subsequent call to claim interface always returns with error -6.

**Comment by dickens** [comment] 2020-11-01 18:10
Closing as duplicate of #803

**Closed by dickens** 2020-11-01 18:10 UTC
