### ISSUE TITLE
In android 10, libusb_init is ok, but libusb_get_device_list return 0

### ISSUE THREAD

**Issue by Sarathmn** [libusb/libusb#754] opened 2020-07-16 09:21 UTC
Iam tring to access a usb device(Cypress) using an android application via libusb 1.0.23.
The android device is rooted. (Samsung galaxy S20 G)

But the but "libusb_get_device_list" function always return 0.
Anybody help me to resolve this issue?

**Comment by dickens** [comment] 2020-07-16 20:15
Duplicate of #584

**Closed by dickens** 2020-07-16 20:15 UTC
Labels: duplicate
