### ISSUE TITLE
LIBUSB_ERROR_BUSY when trying to use device in hotplug callback

### ISSUE THREAD

**Issue by nkovacs** [libusb/libusb#408] opened 2018-03-21 12:49 UTC
The following code gets the android usb accessory protocol version from plugged in devices.
It works fine on devices that are already plugged in when you start the app.
If you plug in a device while the app is running, it fails with LIBUSB_ERROR_BUSY inside the callback, but it succeeds after the callback returns (in main):

```
#include <stdio.h>
#include <stdlib.h>
#include <libusb.h>
#include <unistd.h>

int justArrived;
libusb_device_handle *devHandle;

int hotplug_callback(struct libusb_context *ctx, struct libusb_device *dev,
                     libusb_hotplug_event event, void *user_data) {
  libusb_device_handle *handle = NULL;
  struct libusb_device_descriptor desc;
  int rc;

  (void)libusb_get_device_descriptor(dev, &desc);

  if (desc.idVendor == 0x18D1 &&
       (desc.idProduct == 0x2D00 ||
        desc.idProduct == 0x2D01 ||
        desc.idProduct == 0x2D04 ||
        desc.idProduct == 0x2D05)
     ) {
    return 0;
  }

  if (LIBUSB_HOTPLUG_EVENT_DEVICE_ARRIVED == event) {
    rc = libusb_open(dev, &handle);
    if (LIBUSB_SUCCESS != rc) {
      printf("Could not open USB device\n");
      return 0;
    }
    devHandle = handle;
    uint8_t data[2];
    rc = libusb_control_transfer(handle, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN, 51, 0, 0, &data, 2, 0);
    if (rc < 0) {
      printf("Could not get protocol version: %s\n", libusb_error_name(rc));
      justArrived = 1;
      return 0;
    }
    printf("Protocol version: %d.%d\n", data[0], data[1]);
  } else if (LIBUSB_HOTPLUG_EVENT_DEVICE_LEFT == event) {
  } else {
    printf("Unhandled event %d\n", event);
  }

  return 0;
}

int main (void) {
  libusb_hotplug_callback_handle handle;
  int rc;
  struct timeval tv;
  tv.tv_sec = 0;
  tv.tv_usec = 1000;

  libusb_init(NULL);

  rc = libusb_hotplug_register_callback(NULL, LIBUSB_HOTPLUG_EVENT_DEVICE_ARRIVED |
                                        LIBUSB_HOTPLUG_EVENT_DEVICE_LEFT, 1, LIBUSB_HOTPLUG_MATCH_ANY, LIBUSB_HOTPLUG_MATCH_ANY,
                                        LIBUSB_HOTPLUG_MATCH_ANY, hotplug_callback, NULL,
                                        &handle);

  if (LIBUSB_SUCCESS != rc) {
    printf("Error creating a hotplug callback\n");
    libusb_exit(NULL);
    return EXIT_FAILURE;
  }

  justArrived = 0;
  devHandle = NULL;

  while (1) {
    libusb_handle_events_timeout_completed(NULL, &tv, NULL);
    if (devHandle) {
      if (justArrived) {
        justArrived = 0;
        uint8_t data[2];
        rc = libusb_control_transfer(devHandle, LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_ENDPOINT_IN, 51, 0, 0, &data, 2, 0);
        if (rc < 0) {
          printf("Could not get protocol version: %s\n", libusb_error_name(rc));
        } else {
          printf("Protocol version: %d.%d\n", data[0], data[1]);
        }
      }
      libusb_close(devHandle);
      devHandle = NULL;
    }
  }

  libusb_hotplug_deregister_callback(NULL, handle);
  libusb_exit(NULL);

  return 0;
}
```

I'm using ubuntu 18.04 and the packaged libusb (1.0.21-2). This bug was not present in older versions of ubuntu and it's not present on raspbian either.

**Comment by dickens** [comment] 2018-03-21 16:47
This is by design now. The hotplug handler is called from within event handling context, and calling any synchronous I/O functions will themselves attempt to handle events, which will cause problems.

I'll leave this open until v1.0.22 is released since it contains updates to the documentation indicating this new constraint.

**Comment by dickens** [comment] 2018-03-25 02:03
Documentation has been updated, closing.

**Closed by dickens** 2018-03-25 02:03 UTC
