### ISSUE TITLE
Dose 1.0.23 work with Android? 1.0.22 works.

### ISSUE THREAD

**Issue by TommySato** [libusb/libusb#623] opened 2019-09-18 10:28 UTC
I replaced libusb1.0.so from 1.0.22 to 1.0.23 on my Android studio.
But libusb_get_device_list() always reports no device.
1.0.22 is OK.
linux_default_scan_devices() is not called because of compiler switch.
I think UDEV option have to be ON when compiling. 
Do you know how to turn it on?
I compile libusb1.0.so using ndk-build command on Windows10.

**Comment by laran002** [comment] 2019-11-20 06:28
Is this a duplicate of #584

**Comment by mcuee** [comment] 2020-01-06 02:46
2f3bc98

Maybe this commit has some problems.

**Comment by mcuee** [comment] 2020-01-06 02:47
I have labeled this as duplicate for #584

**Comment by mcuee** [comment] 2020-08-03 01:33
https://github.com/libusb/libusb/pull/760

Not so sure if the above will help.

**Comment by mcuee** [comment] 2020-08-26 02:19
https://github.com/libusb/libusb/pull/760

Maybe users can try Pull Request 760.

**Comment by mcuee** [comment] 2020-12-19 02:31
Close this for now. Please go to the main thread. #584

**Closed by mcuee** 2020-12-19 02:31 UTC
Labels: android, duplicate
