### ISSUE TITLE
Windows enumeration: configuration descriptor info

### ISSUE THREAD

**Issue by mcuee** [libusb/libusb#442] opened 2018-06-11 12:13 UTC
Not really a big issue, just want to point out that the following two devices emit some debug info during the enumeration.

1A40:0201 is a powered hub
04d8:0033 is Microchip PICkit 2 which has two configurations (HID and a custom configuration).

I think it is Windows limitation for the Microchip PICkit 2 and the 2nd configuration is not really needed. USBView also does not list down the configuration descriptor for the 2nd configuration.

For 1A40:0201, USBView can read the configuration descriptor

```
c:\work\libusb\bin-1.0.22\examples\bin64>xusb 0403:6001
Using libusb v1.0.22.11312

Opening device 0403:6001...
libusb: info [cache_config_descriptors] could not access configuration descriptor 0 (dummy) for 'USB\VID_1A40&PID_0201\6&142A28FA&0&5': [31] A device attached to the system is not functioning.
libusb: info [cache_config_descriptors] could not access configuration descriptor 1 (dummy) for 'USB\VID_04D8&PID_0033\PK2NEW': [31] A device attached to the system is not functioning.
  Failed.

c:\work\libusb\bin-1.0.22\examples\bin64>xusb -d 0403:6001
Using libusb v1.0.22.11312

[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.000000] [00001548] libusb: debug [libusb_init] created default context
[ 0.000000] [00001548] libusb: debug [libusb_init] libusb v1.0.22.11312
[ 0.000000] [00001548] libusb: debug [windows_init_dlls] Will use CancelIoEx for I/O cancellation
[ 0.000000] [00001548] libusb: debug [get_windows_version] Windows 8 64-bit
[ 0.000000] [00001548] libusb: debug [windows_init_clock] hires timer available (Frequency: 2734376 Hz)
[ 0.000000] [00001548] libusb: debug [windows_init_clock] timer thread will run on core #0
[ 0.000000] [00001548] libusb: debug [htab_create] using 1021 entries hash table
[ 0.015625] [00001548] libusb: debug [winusbx_init] using libusbK DLL for universal access
[ 0.015625] [00001548] libusb: debug [winusbx_init] libusbK version: 3.0.7.0
[ 0.015625] [00001548] libusb: debug [winusbx_init] initalized sub API libusbK
[ 0.015625] [00001548] libusb: debug [winusbx_init] initalized sub API libusb0
[ 0.015625] [00001548] libusb: debug [winusbx_init] initalized sub API WinUSB
[ 0.015625] [00001548] libusb: debug [windows_init] UsbDk backend is available
[ 0.015625] [00001548] libusb: debug [usbi_add_pollfd] add fd 0 events 1
Opening device 0403:6001...
[ 0.031249] [00001548] libusb: debug [libusb_get_device_list]
[ 0.031249] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [53]
[ 0.046875] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [54]
[ 0.046875] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [55]
[ 0.046875] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [56]
[ 0.046875] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [57]
[ 0.046875] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [58]
[ 0.046875] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [59]
[ 0.046875] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [5A]
[ 0.046875] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [5B]
[ 0.046875] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [5C]
[ 0.046875] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [5D]
[ 0.046875] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [5E]
[ 0.046875] [00001548] libusb: debug [get_api_type] driver(s): BTHUSB
[ 0.046875] [00001548] libusb: debug [get_api_type] lower filter driver(s): bcbtums;btwampfl
[ 0.062499] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [1]
[ 0.062499] [00001548] libusb: debug [get_api_type] driver(s): libusb0
[ 0.062499] [00001548] libusb: debug [get_api_type] matched driver name against libusb0
[ 0.062499] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [A]
[ 0.062499] [00001548] libusb: debug [get_api_type] driver(s): FTDIBUS
[ 0.062499] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [B]
[ 0.062499] [00001548] libusb: debug [get_api_type] driver(s): RtlWlanu
[ 0.062499] [00001548] libusb: debug [get_api_type] upper filter driver(s): vwifibus
[ 0.062499] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [19]
[ 0.062499] [00001548] libusb: debug [get_api_type] driver(s): CH341SER_A64
[ 0.062499] [00001548] libusb: debug [get_api_type] upper filter driver(s): serenum
[ 0.062499] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [25]
[ 0.062499] [00001548] libusb: debug [get_api_type] driver(s): usbccgp
[ 0.062499] [00001548] libusb: debug [get_api_type] matched driver name against Composite API
[ 0.078123] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [40]
[ 0.078123] [00001548] libusb: debug [get_api_type] driver(s): USBSTOR
[ 0.078123] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [41]
[ 0.078123] [00001548] libusb: debug [get_api_type] driver(s): HidUsb
[ 0.078123] [00001548] libusb: debug [get_api_type] matched driver name against HID API
[ 0.078123] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [42]
[ 0.078123] [00001548] libusb: debug [get_api_type] driver(s): USBSTOR
[ 0.078123] [00001548] libusb: debug [winusb_get_device_list] allocating new device for session [43]
[ 0.078123] [00001548] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_8086&DEV_27CB&SUBSYS_2A8C103C&REV_01\3&11583659&0&EB' bus number 1
[ 0.078123] [00001548] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_8086&DEV_27C8&SUBSYS_2A8C103C&REV_01\3&11583659&0&E8' bus number 2
[ 0.093748] [00001548] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_8086&DEV_27C9&SUBSYS_2A8C103C&REV_01\3&11583659&0&E9' bus number 3
[ 0.093748] [00001548] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_1033&DEV_0194&SUBSYS_00000000&REV_03\FFFFFFFFFFFFFFFF00' bus number 4
[ 0.093748] [00001548] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_8086&DEV_27CA&SUBSYS_2A8C103C&REV_01\3&11583659&0&EA' bus number 5
[ 0.093748] [00001548] libusb: debug [enumerate_hcd_root_hub] assigning HCD 'PCI\VEN_8086&DEV_27CC&SUBSYS_2A8C103C&REV_01\3&11583659&0&EF' bus number 6
[ 0.093748] [00001548] libusb: debug [init_device] (bus: 1, addr: 0, depth: 0, port: 0): 'USB\ROOT_HUB\4&1D76050&0'
[ 0.093748] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [5C]
[ 0.093748] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.093748] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 41 bytes)
[ 0.093748] [00001548] libusb: debug [init_device] (bus: 4, addr: 4, depth: 2, port: 1): 'USB\VID_0BDA&PID_5411\7&8604D34&0&1'
[ 0.109375] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [5A]
[ 0.109375] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.109375] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 31 bytes)
[ 0.109375] [00001548] libusb: debug [init_device] (bus: 4, addr: 2, depth: 2, port: 1): 'USB\VID_0BDA&PID_0411\7&48EBE67&0&1'
[ 0.109375] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [59]
[ 0.109375] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.109375] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 31 bytes)
[ 0.109375] [00001548] libusb: debug [init_device] (bus: 4, addr: 1, depth: 1, port: 1): 'USB\VID_0BDA&PID_0411\6&38FE5F06&0&1'
[ 0.109375] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [5B]
[ 0.109375] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.109375] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 41 bytes)
[ 0.125004] [00001548] libusb: debug [init_device] (bus: 4, addr: 3, depth: 1, port: 3): 'USB\VID_0BDA&PID_5411\6&38FE5F06&0&3'
[ 0.125004] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [1]
[ 0.125004] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.125004] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 218 bytes)
[ 0.125004] [00001548] libusb: debug [init_device] (bus: 6, addr: 6, depth: 2, port: 7): 'USB\VID_0A5C&PID_21E8\5CF3708A6D48'
[ 0.125004] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [5E]
[ 0.125004] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.125004] [00001548] libusb: info [cache_config_descriptors] could not access configuration descriptor 0 (dummy) for 'USB\VID_1A40&PID_0201\6&142A28FA&0&5': [31] A device attached to the system is not functioning.
[ 0.125004] [00001548] libusb: debug [init_device] (bus: 6, addr: 5, depth: 2, port: 5): 'USB\VID_1A40&PID_0201\6&142A28FA&0&5'
[ 0.125004] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [42]
[ 0.204053] [00001548] libusb: debug [init_device] found 2 configurations (active conf: 1)
[ 0.204053] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 41 bytes)
[ 0.204053] [00001548] libusb: info [cache_config_descriptors] could not access configuration descriptor 1 (dummy) for 'USB\VID_04D8&PID_0033\PK2NEW': [31] A device attached to the system is not functioning.
[ 0.204053] [00001548] libusb: debug [init_device] (bus: 6, addr: 7, depth: 3, port: 3): 'USB\VID_04D8&PID_0033\PK2NEW'
[ 0.204053] [00001548] libusb: debug [init_device] (bus: 5, addr: 0, depth: 0, port: 0): 'USB\ROOT_HUB\4&1397E823&0'
[ 0.204053] [00001548] libusb: debug [discovered_devs_append] need to increase capacity
[ 0.204053] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [25]
[ 0.204053] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.204053] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 39 bytes)
[ 0.204053] [00001548] libusb: debug [init_device] (bus: 6, addr: 4, depth: 2, port: 3): 'USB\VID_1A86&PID_7523\6&142A28FA&0&3'
[ 0.204053] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [19]
[ 0.204053] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.204053] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 83 bytes)
[ 0.204053] [00001548] libusb: debug [init_device] (bus: 4, addr: 5, depth: 1, port: 2): 'USB\VID_2357&PID_0106\123456'
[ 0.204053] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [41]
[ 0.204053] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.204053] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 44 bytes)
[ 0.204053] [00001548] libusb: debug [init_device] (bus: 4, addr: 6, depth: 3, port: 2): 'USB\VID_0781&PID_5581\4C531001401224105220'
[ 0.204053] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [A]
[ 0.204053] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.219688] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 32 bytes)
[ 0.219688] [00001548] libusb: debug [init_device] (bus: 2, addr: 1, depth: 1, port: 1): 'USB\VID_0FCF&PID_1009\111'
[ 0.219688] [00001548] libusb: debug [init_device] (bus: 6, addr: 0, depth: 0, port: 0): 'USB\ROOT_HUB20\4&1AB460DB&0'
[ 0.219688] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [43]
[ 0.219688] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.219688] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 32 bytes)
[ 0.219688] [00001548] libusb: debug [init_device] (bus: 6, addr: 1, depth: 1, port: 7): 'USB\VID_058F&PID_6366\058F63666433'
[ 0.219688] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [5D]
[ 0.219688] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.219688] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 41 bytes)
[ 0.219688] [00001548] libusb: debug [init_device] (bus: 6, addr: 2, depth: 1, port: 4): 'USB\VID_1A40&PID_0201\5&2B206C2B&0&4'
[ 0.219688] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [40]
[ 0.219688] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.235313] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 84 bytes)
[ 0.235313] [00001548] libusb: debug [init_device] (bus: 3, addr: 1, depth: 1, port: 1): 'USB\VID_046D&PID_C52B\5&1AB0C0B&0&1'
[ 0.235313] [00001548] libusb: debug [discovered_devs_append] need to increase capacity
[ 0.235313] [00001548] libusb: debug [init_device] (bus: 3, addr: 0, depth: 0, port: 0): 'USB\ROOT_HUB\4&287CBA06&0'
[ 0.235313] [00001548] libusb: debug [init_device] (bus: 4, addr: 0, depth: 0, port: 0): 'USB\ROOT_HUB30\5&345C3975&0&0'
[ 0.235313] [00001548] libusb: debug [winusb_get_device_list] extra GUID: {8D891245-36D8-4ECA-9A92-481F0A912DCF}
[ 0.235313] [00001548] libusb: debug [winusb_get_device_list] found existing device for session [B]
[ 0.235313] [00001548] libusb: debug [init_device] found 1 configurations (active conf: 1)
[ 0.235313] [00001548] libusb: debug [cache_config_descriptors] cached config descriptor 0 (bConfigurationValue=1, 32 bytes)
[ 0.235313] [00001548] libusb: debug [init_device] (bus: 6, addr: 8, depth: 2, port: 2): 'USB\VID_0403&PID_6001\A8007UB5'
[ 0.235313] [00001548] libusb: debug [init_device] (bus: 2, addr: 0, depth: 0, port: 0): 'USB\ROOT_HUB\4&288D5874&0'
[ 0.235313] [00001548] libusb: debug [winusb_get_device_list] setting composite interface for [40]:
[ 0.235313] [00001548] libusb: debug [set_composite_interface] interface[1] = \\.\HID#VID_046D&PID_C52B&MI_01&COL01#7&56C8C02&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.235313] [00001548] libusb: debug [winusb_get_device_list] setting composite interface for [40]:
[ 0.235313] [00001548] libusb: debug [set_composite_interface] interface[1] already set - ignoring HID collection: HID\VID_046D&PID_C52B&MI_01&COL03\7&56C8C02&0&0002
[ 0.250938] [00001548] libusb: debug [winusb_get_device_list] setting composite interface for [40]:
[ 0.250938] [00001548] libusb: debug [set_composite_interface] interface[1] already set - ignoring HID collection: HID\VID_046D&PID_C52B&MI_01&COL04\7&56C8C02&0&0003
[ 0.250938] [00001548] libusb: debug [winusb_get_device_list] setting HID interface for [42]:
[ 0.250938] [00001548] libusb: debug [set_hid_interface] interface[0] = \\.\HID#VID_04D8&PID_0033#8&BD5B18B&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.250938] [00001548] libusb: debug [winusb_get_device_list] setting composite interface for [40]:
[ 0.250938] [00001548] libusb: debug [set_composite_interface] interface[2] = \\.\HID#VID_046D&PID_C52B&MI_02&COL01#7&1E6AB1C0&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.250938] [00001548] libusb: debug [winusb_get_device_list] setting composite interface for [40]:
[ 0.250938] [00001548] libusb: debug [set_composite_interface] interface[2] already set - ignoring HID collection: HID\VID_046D&PID_C52B&MI_02&COL02\7&1E6AB1C0&0&0001
[ 0.250938] [00001548] libusb: debug [winusb_get_device_list] setting composite interface for [40]:
[ 0.250938] [00001548] libusb: debug [set_composite_interface] interface[2] already set - ignoring HID collection: HID\VID_046D&PID_C52B&MI_02&COL03\7&1E6AB1C0&0&0002
[ 0.250938] [00001548] libusb: debug [winusb_get_device_list] setting composite interface for [40]:
[ 0.250938] [00001548] libusb: debug [set_composite_interface] interface[0] = \\.\HID#VID_046D&PID_C52B&MI_00#7&2943C9C4&0&0000#{4D1E55B2-F16F-11CF-88CB-001111000030}
[ 0.250938] [00001548] libusb: debug [winusb_get_device_list] setting composite interface for [40]:
[ 0.250938] [00001548] libusb: debug [set_composite_interface] interface[1] already set - ignoring HID collection: HID\VID_046D&PID_C52B&MI_01&COL02\7&56C8C02&0&0001
[ 0.250938] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.250938] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.250938] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_get_device_descriptor]
[ 0.266563] [00001548] libusb: debug [libusb_open] open 6.8
[ 0.266563] [00001548] libusb: debug [winusb_open] unsupported API call for 'open' (unrecognized device driver)
[ 0.266563] [00001548] libusb: debug [libusb_open] open 6.8 returns -12
[ 0.266563] [00001548] libusb: debug [libusb_unref_device] destroy device 1.0
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 4.4
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 4.3
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 6.6
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 6.7
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 6.5
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 5.0
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 6.4
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 4.5
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 4.6
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 4.2
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 4.1
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 2.1
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 6.1
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 3.1
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 3.0
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 4.0
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 6.8
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 6.2
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 6.0
[ 0.282187] [00001548] libusb: debug [libusb_unref_device] destroy device 2.0
  Failed.
[ 0.297812] [00001548] libusb: debug [libusb_exit]
[ 0.297812] [00001548] libusb: debug [libusb_exit] destroying default context
[ 0.297812] [00001548] libusb: debug [usbi_remove_pollfd] remove fd 0
[ 0.297812] [000032c8] libusb: debug [windows_clock_gettime_threaded] timer thread quitting
```

**Comment by mcuee** [comment] 2018-06-11 13:27
usbview output for the hub.

```
External Hub: USB#VID_0BDA&PID_5411#6&38fe5f06&0&3#{f18a0e88-c30c-11d0-8815-00a0c906bed8}
Hub Power:               Self Power
Number of Ports:         4
Power switching:         Individual
Compound device:         No
Over-current Protection: Individual

Device Descriptor:
bcdUSB:             0x0210
bDeviceClass:         0x09
bDeviceSubClass:      0x00
bDeviceProtocol:      0x02
bMaxPacketSize0:      0x40 (64)
idVendor:           0x0BDA (Realtek Semiconductor Corp.)
idProduct:          0x5411
bcdDevice:          0x0117
iManufacturer:        0x01
iProduct:             0x02
iSerialNumber:        0x00
bNumConfigurations:   0x01

ConnectionStatus: DeviceConnected
Current Config Value: 0x01
Device Bus Speed:     High
Device Address:       0x03
Open Pipes:              1

Endpoint Descriptor:
bEndpointAddress:     0x81  IN
Transfer Type:   Interrupt
wMaxPacketSize:     0x0001 (1)
bInterval:            0x0C

Configuration Descriptor:
wTotalLength:       0x0029
bNumInterfaces:       0x01
bConfigurationValue:  0x01
iConfiguration:       0x00
bmAttributes:         0xE0 (Bus Powered Self Powered Remote Wakeup)
MaxPower:             0x00 (0 Ma)

Interface Descriptor:
bInterfaceNumber:     0x00
bAlternateSetting:    0x00
bNumEndpoints:        0x01
bInterfaceClass:      0x09 (Hub)
bInterfaceSubClass:   0x00
bInterfaceProtocol:   0x01
iInterface:           0x00

Endpoint Descriptor:
bEndpointAddress:     0x81  IN
Transfer Type:   Interrupt
wMaxPacketSize:     0x0001 (1)
bInterval:            0x0C

Interface Descriptor:
bInterfaceNumber:     0x00
bAlternateSetting:    0x01
bNumEndpoints:        0x01
bInterfaceClass:      0x09 (Hub)
bInterfaceSubClass:   0x00
bInterfaceProtocol:   0x02
iInterface:           0x00

Endpoint Descriptor:
bEndpointAddress:     0x81  IN
Transfer Type:   Interrupt
wMaxPacketSize:     0x0001 (1)
bInterval:            0x0C

```

**Comment by dickens** [comment] 2020-08-17 21:22
I think such errors result from the device not responding correctly to a descriptor request.  Since this the hub is using the Microsoft-provided driver, the issue is almost certainly going to be with the device.

As I don't think there's any recourse for libusb, I'm going to close this issue.  Feel free to re-open if new information comes up.

**Closed by dickens** 2020-08-17 21:22 UTC
Labels: windows
