### ISSUE TITLE
CreateProcess(NULL, /usr/bin/mkdir -p os, ...) failed.

### ISSUE THREAD

**Issue by wolfgangwayland7** [libusb/libusb#21] opened 2014-06-29 08:47 UTC
With latest version of libusb libusb-1.0.18,  I  successfully  ran  "./configure" on cygwin,  and  got a weird make error, see below;
``` 
make[1]: Entering directory `C:/cygwin/home/libusb-1.0.18/libusb'

  CC     libusb_1_0_la-core.lo
  CC     libusb_1_0_la-descriptor.lo
  CC     libusb_1_0_la-io.lo
  CC     libusb_1_0_la-strerror.lo
  CC     libusb_1_0_la-sync.lo
  CC     libusb_1_0_la-hotplug.lo
process_begin: CreateProcess(NULL, /usr/bin/mkdir -p os, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [os/.dirstamp] Error 2
make[1]: Leaving directory `C:/cygwin/home/libusb-1.0.18/libusb'
make: *** [check-recursive] Error 1
```
Also libusb-compat-0.1.5 requires a previous version of libusb to be installed, and ask's for disks that don't exist?!#?

Any suggestions. Is this a broken library as far as "windows"  compiling is concerned?  I don't have linux installed yet..

**Comment by pbatard** [comment] 2015-02-16 23:23
Since we haven't hear back from OP, I will be closing this issue.

**Closed by pbatard** 2015-02-16 23:23 UTC

**Comment by benharper123** [comment] 2015-02-23 15:46
This issue can be caused by having a "make.exe" in your path that takes precedence over the cygwin-provided "make"
