### ISSUE TITLE
Detaching usbfs

### ISSUE THREAD

**Issue by lo1ol** [libusb/libusb#985] opened 2021-08-26 12:49 UTC
Hi! 

I recently faced into with some problem of using usb passthrough with qemu. The problem is that I can't detach device handeled by usbfs driver. 

This behaviar was added by this commit https://github.com/libusb/libusb/commit/34807a115263ff4fe94b1dc894f93f076e759d5f 

May you please explain my, why we can safely detach any other driver except usbfs? Is it disadvatage of usbfs driver? 

I tried monually remove this checks and get successfull pathrough to qemu. Prevous user of  device got LIBUSB_ERROR_NODEVICE error. I think it's good behaviour if pretty handle it.

**Comment by mcuee** [comment] 2021-09-08 08:33
@lo1ol I will close this one as per the following libusb documentation. You may want to engage qemu people to see if they can remove that reset call.
https://libusb.sourceforge.io/api-1.0/libusb_caveats.html

The problem is that any other program could reset the device your program is working with, at any time. libusb does not offer a mechanism to inform you when this has happened, so if someone else resets your device it will not be clear to your own program why the device state has changed.

Ultimately, this is a limitation of writing drivers in user space. Separation from the USB stack in the underlying kernel makes it difficult for the operating system to deliver such notifications to your program. The Linux kernel USB stack allows such reset notifications to be delivered to in-kernel USB drivers, but it is not clear how such notifications could be delivered to second-class drivers that live in user space.

**Closed by mcuee** 2021-09-08 08:33 UTC
Labels: linux
